version: '3'
services:
  front:
    restart: always
    build:
      context: ./
      dockerfile: .docker/front/Dockerfile
    networks:
      - web
    ports:
      - "8084:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prochainbus.rule=Host(`le-prochain-bus.lucas-trebouet.fr`)"
      - "traefik.http.routers.prochainbus.entrypoints=websecure"
  back:
    restart: always
    build:
      context: ./
      dockerfile: .docker/back/Dockerfile
    ports:
      - "8085:8081"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prochainbusws.rule=Host(`le-prochain-bus-ws.lucas-trebouet.fr`)"
      - "traefik.http.routers.prochainbusws.entrypoints=websecure"
networks:
  web:
    external: true