---
# tasks file for front

- name: Create app directory
  file:
    path: /home/lucas/app/nextbus
    state: directory
    mode: '0755'

- name: Copy app
  copy:
    src: ../back/{{ item }}
    dest: /home/lucas/app/nextbus/back
    owner: lucas
    group: lucas
    mode: '0755'
  with_items:
    - package.json
    - package-lock.json
    - main.js

- name: Copy Docker files
  copy:
    src: ../.docker/back/
    dest: /home/lucas/app/nextbus/.docker/back/
    owner: lucas
    group: lucas
    mode: '0755'

- name: Install .env
  template:
    src: back/templates/.env.j2
    dest: /home/lucas/app/nextbus/back/.env
    mode: '0644'
  

- name: npm ci
  command: chdir=/home/lucas/app/nextbus/ docker-compose up -d --build